name: Run tests

on:
  workflow_dispatch:  # allow manual trigger
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macOS-latest]
        python-version: ["3.10"]

    steps:

    - name: macOS Notarize -- Install Certificates
      if: runner.os == 'macOS'
      run: |
        echo ${{ secrets.CERTIFICATE_P12 }} | base64 --decode > certificate.p12
        security import certificate.p12 -P ${{ secrets.CERTIFICATE_PASSWORD }}
        security create-keychain -p fgKeychain fg.keychain
        security default-keychain -s fg.keychain
        security set-keychain-settings -l -u -t 8000
        security unlock-keychain -p fgKeychain fg.keychain
        security import certificate.p12 -k fg.keychain -P ${{ secrets.CERTIFICATE_PASSWORD }} -T /usr/bin/codesign
        security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k fgKeychain fg.keychain
        rm -fr *.p12
        # security find-identity -v -p codesigning

    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build app
      run: |
        pyinstaller FontraPak.spec -y

    - name: macOS Notarize -- Codesign and Notarize
      if: runner.os == 'macOS'
      run: |
        macos/codesign_app.sh "${{ secrets.CODESIGN_NAME }}" "dist/Fontra Pak.app" macos/entitlements.plist
        python macos/build_dmg.py "dist/Fontra Pak.app" "dist/FontraPak.dmg"
        codesign --sign "${{ secrets.CODESIGN_NAME }}" "dist/FontraPak.dmg"
        xcrun altool --notarize-app --primary-bundle-id "xyz.fontra.fontra-pak" \
                     --username "${{ secrets.NOTARIZE_DEVELOPER }}" \
                     --password "${{ secrets.NOTARIZE_PASSWORD }}" \
                     --file dist/FontraPak.dmg \
                     --output-format xml \
                     | python macos/await_notarization.py "${{ secrets.NOTARIZE_DEVELOPER }}" "${{ secrets.NOTARIZE_PASSWORD }}"
        xcrun stapler staple "dist/FontraPak.dmg"

    - name: Storing Windows Artifacts
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@master
      with:
        name: Fontra Pak Windows
        path: ./dist/*.exe

    - name: Storing macOS Artifacts
      if: runner.os == 'macOS'
      uses: actions/upload-artifact@master
      with:
        name: Fontra Pak macOS
        path: ./dist/*.dmg
